---
###############################################################################
# Default
###############################################################################
# Ensure no runtime errors as it is just a lightweight template wrapper.
#
# Tests:
# * Ensure no run-time errors.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        logrotate_local:
          - service: 'dpkg'
            state: 'absent'
          - service: 'apt'
            state: 'present'
            config:
              - logs:
                  - '/var/log/apt/term.log'
                rotate:
                  count: 12
                  period: 'monthly'
                  compress: true
                  missing_ok: true
                  if_empty: false
              - logs:
                  - '/var/log/apt/history.log'
                  - '/var/log/apt/multi-logs-format-test.log'
                rotate:
                  count: 12
                  period: 'monthly'
                  compress: true
                  missing_ok: true
                  if_empty: false
platforms:
  - name: 'logrotate-debian-13-default'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    # - 'prepare'
    - 'converge'
    - 'idempotence'
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
