---
- name: 'Verify | absent state removes file'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | absent state removes file | dpkg'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Verify | absent state removes file | dpkg'
        test_file: '/etc/logrotate.d/dpkg'
        test_owner: '{{ omit }}'
        test_group: '{{ omit }}'
        test_mode: '{{ omit }}'
        test_state: 'absent'
        test_diff: true

- name: 'Verify | global configuration'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | global configuration | logrotate.conf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | global configuration | logrotate.conf'
        test_src: 'files/logrotate.conf'
        test_file: '/etc/logrotate.conf'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_diff: true

- name: 'Verify | local configuration'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | local configuration | logrotate.conf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | local configuration | logrotate.conf'
        test_src: 'files/apt'
        test_file: '/etc/logrotate.d/apt'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_diff: true
